name: deploy_on_vps

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Copy dist recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: schedule
        remote: ${{ secrets.ALIEN_RAILS_IMG_SCHEDULE_PATH }}
        host: ${{ secrets.ALIEN_HOST }}
        port: ${{ secrets.ALIEN_SSH_PORT }}
        username: ${{ secrets.ALIEN_USER }}
        password: ${{ secrets.ALIEN_PASSWORD }}
    - name: Assets:precompile
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.ALIEN_HOST }}
        port: ${{ secrets.ALIEN_SSH_PORT }}
        username: ${{ secrets.ALIEN_USER }}
        password: ${{ secrets.ALIEN_PASSWORD }}
        script_stop: true
        script: |
          cd ${{ secrets.ALIEN_SCRIPT_PATH }}
          pwd
          ./precompile.sh
